export { default as HomePage } from './HomePage/HomePage'
export { default as CheckoutPage } from './CheckoutPage/CheckoutPage'
export { default as LoginPage } from './LoginPage/LoginPage'
export { default as OrdersPage } from './OrdersPage/OrdersPage'
export { default as PaymentPage } from './PaymentPage/PaymentPage'
